### ISSUE TITLE
Text Inputs/Solid not displaying correctly in Safari 13

### ISSUE THREAD

**Issue by bamccaul-dev** [Pageworks/web-components-library#2]
The text inputs/solid display has an issue with the cursor displaying beyond the input. See the below screen shots.
![Screen Shot 2019-09-23 at 10 33 46 AM](https://user-images.githubusercontent.com/53950292/65435119-f346c580-dded-11e9-8a59-144cbdce40ea.png)
![Screen Shot 2019-09-23 at 10 32 51 AM](https://user-images.githubusercontent.com/53950292/65435120-f346c580-dded-11e9-85e0-5e2c2caccd59.png)

There is also an issue with the text input holding on to the focus in Safari 13. If you enter the input, it validates as invalid, and the whenever you navigate away from from that (I was clicking the url bar) it keeps the focus on the input.

**Comment by codewithkyle** [comment]
This issue was fixed and deployed with PR #3
